// Road to Purr-fection content. Everything the site shows lives in this file.
// To add a flashcard or a question, see CONTRIBUTING.md.
// Sources: the official Associate exam guide (May 2026) and the Databricks docs.

const EXAM = {
  questions: 45, minutes: 90, fee: "USD 200", validity: "2 years",
  delivery: "Online proctored or test center",
  note: "Code on the exam is shown in SQL when possible, otherwise Python."
};

const SECTIONS = [
  { id: "s1", n: 1, name: "Databricks Intelligence Platform", weight: 6, mock: 3,
    objectives: [
      "Core components: the platform architecture, Delta Lake and Unity Catalog",
      "Compute options, their limits and cost models, and which one fits each workload"
    ],
    know: [
      "The control plane (web app, job scheduler, notebook and job metadata) runs in the Databricks account. Your data stays in your own cloud object storage.",
      "Classic compute runs in your cloud account. Serverless compute runs in a compute plane that Databricks manages.",
      "Delta Lake stores data as Parquet files plus a transaction log (_delta_log). That log gives ACID transactions, time travel and audit history.",
      "Unity Catalog governs data with a three level name: catalog.schema.object.",
      "All purpose compute is for interactive work. Jobs compute is created for a run and shut down after it, at a lower rate. Serverless starts in seconds with no cluster setup.",
      "SQL warehouses run SQL and BI workloads. Serverless SQL warehouses start fastest and scale for many users.",
      "Pools keep idle instances ready so clusters start faster."
    ],
    docs: [
      ["Platform introduction", "https://docs.databricks.com/aws/en/introduction/"],
      ["Delta Lake", "https://docs.databricks.com/aws/en/delta/"],
      ["Compute", "https://docs.databricks.com/aws/en/compute/"],
      ["SQL warehouses", "https://docs.databricks.com/aws/en/compute/sql-warehouse/"]
    ] },
  { id: "s2", n: 2, name: "Data Ingestion and Loading", weight: 21, mock: 9,
    objectives: [
      "Batch, streaming and incremental loading, from local files and Lakeflow Connect standard and managed connectors",
      "COPY INTO for incremental loads from cloud object storage into Unity Catalog tables",
      "Auto Loader with schema enforcement and schema evolution, in directory listing or file notification mode",
      "Configure Lakeflow Connect for enterprise sources",
      "JDBC, ODBC or REST clients in notebooks, scheduled with Lakeflow Jobs",
      "Choose between Auto Loader, Lakeflow Connect, partner connectors and other methods",
      "Ingest semi structured and unstructured data such as nested JSON"
    ],
    know: [
      "COPY INTO is idempotent. It tracks which files it already loaded and skips them on the next run.",
      "Auto Loader is spark.readStream.format(\"cloudFiles\"). It processes new files incrementally and records progress in a checkpoint.",
      "cloudFiles.schemaLocation is where Auto Loader stores the inferred schema and its changes.",
      "For JSON and CSV, Auto Loader infers every column as a string unless you set cloudFiles.inferColumnTypes or give schema hints.",
      "Default schema evolution mode is addNewColumns: the stream stops when a new column appears, the schema is updated, and the next start includes the column.",
      "Data that does not match the schema lands in the _rescued_data column instead of being lost.",
      "Directory listing works out of the box. File notification mode uses cloud events and queues, which scales better for directories with very many files.",
      "trigger(availableNow=True) processes everything available, in as many batches as needed, then stops. Good for scheduled incremental runs.",
      "Lakeflow Connect managed connectors ingest from SaaS apps and databases (for example Salesforce, ServiceNow, SQL Server) with little or no code.",
      "JDBC reads use spark.read.format(\"jdbc\") with url and dbtable options."
    ],
    docs: [
      ["Lakeflow Connect", "https://docs.databricks.com/aws/en/ingestion/lakeflow-connect/"],
      ["Auto Loader", "https://docs.databricks.com/aws/en/ingestion/cloud-object-storage/auto-loader/"],
      ["Auto Loader schema inference and evolution", "https://docs.databricks.com/aws/en/ingestion/cloud-object-storage/auto-loader/schema"],
      ["COPY INTO", "https://docs.databricks.com/aws/en/ingestion/cloud-object-storage/copy-into/"],
      ["Connect to data sources", "https://docs.databricks.com/aws/en/connect/"],
      ["Semi structured data", "https://docs.databricks.com/aws/en/semi-structured/"]
    ] },
  { id: "s3", n: 3, name: "Data Transformation and Modeling", weight: 22, mock: 10,
    objectives: [
      "Clean bronze data with PySpark or SQL: handle nulls, standardize types, write silver tables",
      "Combine DataFrames: inner, left, broadcast and cross joins, multiple keys, union and union all",
      "Add, drop, split and rename columns, filter rows, explode arrays",
      "Deduplicate and aggregate: count, approximate count distinct, mean, summary",
      "Basic tuning: spark.sql.shuffle.partitions, spark.default.parallelism, executor and driver memory, spark.sql.autoBroadcastJoinThreshold",
      "Gold layer objects in Unity Catalog: materialized views, views, streaming tables, tables",
      "Data quality checks and validation rules for silver and gold"
    ],
    know: [
      "Medallion: bronze keeps raw data with a schema applied, silver is cleaned and conformed, gold is aggregated for BI.",
      "In PySpark, DataFrame.union keeps duplicates, like SQL UNION ALL, and matches columns by position. unionByName matches by name. SQL UNION removes duplicates.",
      "A broadcast join sends a small table to every executor, which avoids shuffling the large table. Use F.broadcast(small_df).",
      "spark.sql.autoBroadcastJoinThreshold sets the size under which Spark broadcasts automatically (10 MB by default). Setting it to -1 turns automatic broadcast off.",
      "spark.sql.shuffle.partitions defaults to 200. Lower it for small data, raise it for large shuffles. Adaptive query execution can coalesce partitions for you.",
      "dropDuplicates([\"key\"]) keeps one row per key. distinct() drops rows that are identical in every column.",
      "approx_count_distinct is much faster than an exact distinct count on large data.",
      "explode turns each array element into its own row. split turns a string into an array.",
      "A view stores only the query. A materialized view stores precomputed results and is refreshed. A streaming table processes new rows incrementally, each one once.",
      "Pipeline expectations: EXPECT alone keeps bad rows and records metrics, ON VIOLATION DROP ROW drops them, ON VIOLATION FAIL UPDATE stops the update.",
      "count_if(col IS NULL) counts nulls in a column."
    ],
    docs: [
      ["Medallion architecture", "https://docs.databricks.com/aws/en/lakehouse/medallion.html"],
      ["PySpark on Databricks", "https://docs.databricks.com/aws/en/pyspark/"],
      ["Adaptive query execution", "https://docs.databricks.com/aws/en/optimizations/aqe"],
      ["Materialized views", "https://docs.databricks.com/aws/en/views/materialized.html"],
      ["Streaming tables", "https://docs.databricks.com/aws/en/tables/streaming"],
      ["Pipeline expectations", "https://docs.databricks.com/aws/en/dlt/expectations"]
    ] },
  { id: "s4", n: 4, name: "Working with Lakeflow Jobs", weight: 16, mock: 7,
    objectives: [
      "Control flow: retries, If/else branching and For each loops",
      "Notebook, SQL query, dashboard and pipeline tasks, and their dependencies in the task graph",
      "Schedules and trigger types: scheduled, file arrival, table update",
      "Choose time based or data driven triggers"
    ],
    know: [
      "A job is a graph of tasks. A task runs after the tasks in its Depends on list, based on its Run if condition (All succeeded is the default).",
      "If/else condition tasks branch on a value, such as a job parameter or a task value.",
      "For each tasks run a nested task once per item in a list, with optional concurrency.",
      "Retries are set per task, with a count and an interval. Use them for transient failures.",
      "Scheduled triggers use a simple interval or Quartz cron syntax with a time zone.",
      "File arrival triggers start a run when new files land in a Unity Catalog volume or external location.",
      "Table update triggers start a run when a source table is updated.",
      "Repair run reruns only the failed tasks and the tasks that depend on them.",
      "Notifications on start, success, failure or duration go to email or to destinations such as a webhook or Slack.",
      "Pick a data driven trigger when data arrives at irregular times; pick a schedule when the business needs a fixed time."
    ],
    docs: [
      ["Lakeflow Jobs", "https://docs.databricks.com/aws/en/jobs/"],
      ["Control flow", "https://docs.databricks.com/aws/en/jobs/control-flow"],
      ["Triggers", "https://docs.databricks.com/aws/en/jobs/triggers"],
      ["Monitor jobs", "https://docs.databricks.com/aws/en/jobs/monitor"]
    ] },
  { id: "s5", n: 5, name: "Implementing CI/CD", weight: 10, mock: 5,
    objectives: [
      "Git folders in the workspace: create and switch branches, commit, push, pull requests",
      "Bundle variables and target overrides for dev, test and prod",
      "Deploy bundles to package and promote jobs, pipelines and other assets",
      "Use the Databricks CLI to validate, deploy and manage bundles in CI/CD"
    ],
    know: [
      "Git folders (formerly Repos) clone a remote repo into the workspace. From the Git dialog you create branches, commit and push, pull, and merge.",
      "Pull brings remote changes into your Git folder. Push sends your commits to the remote.",
      "Declarative Automation Bundles (formerly Databricks Asset Bundles) describe resources as code in databricks.yml.",
      "targets define environments such as dev and prod. Each target can override settings such as the workspace host or a variable.",
      "Variables are declared under variables and referenced as ${var.name}.",
      "mode: development prefixes resource names with your user name and pauses schedules. mode: production is for the shared deployment.",
      "CLI flow: databricks bundle init, databricks bundle validate, databricks bundle deploy -t <target>, databricks bundle run, databricks bundle destroy."
    ],
    docs: [
      ["Git folders", "https://docs.databricks.com/aws/en/repos/"],
      ["Bundles", "https://docs.databricks.com/aws/en/dev-tools/bundles/"],
      ["Databricks CLI", "https://docs.databricks.com/aws/en/dev-tools/cli/"]
    ] },
  { id: "s6", n: 6, name: "Troubleshooting, Monitoring, and Optimization", weight: 10, mock: 4,
    objectives: [
      "Compare job durations against historical runs in the Lakeflow Jobs run history",
      "Monitor pipeline health in the Jobs UI: statuses, task graph, run times, failure rates",
      "Find skew, shuffle and disk spill in Spark UI stage metrics",
      "Liquid clustering and predictive optimization",
      "Diagnose cluster startup failures, library conflicts and out of memory errors"
    ],
    know: [
      "Skew: most tasks finish quickly but a few take much longer and read far more shuffle data. Adaptive query execution can split skewed join partitions.",
      "Spill: Spill (Memory) and Spill (Disk) in a stage mean partitions did not fit in memory. More partitions or more memory reduces it.",
      "Large shuffle read and write means data is moving between executors, usually from joins, groupBy or repartition.",
      "Liquid clustering (CLUSTER BY) replaces partitioning and ZORDER. Clustering keys can change without rewriting the table. CLUSTER BY AUTO lets Databricks pick keys.",
      "Predictive optimization runs maintenance such as OPTIMIZE, VACUUM and ANALYZE automatically on Unity Catalog managed tables.",
      "OPTIMIZE compacts small files. VACUUM removes files no longer referenced, after the retention period (7 days by default), which limits time travel.",
      "collect() on a large DataFrame pulls everything to the driver and can cause a driver out of memory error.",
      "Notebook scoped libraries (%pip install) avoid version conflicts between notebooks on the same cluster.",
      "Cluster start failures often come from cloud quota limits, unavailable instance types or failing init scripts. The event log shows the cause."
    ],
    docs: [
      ["Spark UI guide", "https://docs.databricks.com/aws/en/optimizations/spark-ui-guide/"],
      ["Liquid clustering", "https://docs.databricks.com/aws/en/delta/clustering.html"],
      ["Predictive optimization", "https://docs.databricks.com/aws/en/optimizations/predictive-optimization.html"],
      ["Compute troubleshooting", "https://docs.databricks.com/aws/en/compute/troubleshooting/"]
    ] },
  { id: "s7", n: 7, name: "Governance and Security", weight: 15, mock: 7,
    objectives: [
      "Managed and external tables in Unity Catalog: create, modify, delete, convert",
      "GRANT, REVOKE and DENY for users, groups and service principals at the right level",
      "Column masks and row level security by group",
      "Unity Catalog ABAC policies for central row filtering and column masking"
    ],
    know: [
      "Managed table: Unity Catalog manages the data files. DROP TABLE deletes the data too (UNDROP can recover it for a limited time).",
      "External table: data lives at a LOCATION you manage. DROP TABLE removes only the metadata; the files stay.",
      "ALTER TABLE ... SET MANAGED converts an external table to a managed table.",
      "To query a table a user needs USE CATALOG on the catalog, USE SCHEMA on the schema and SELECT on the table.",
      "Privileges are inherited downward: SELECT granted on a catalog covers its schemas and tables, including ones created later.",
      "Syntax: GRANT SELECT ON TABLE main.sales.orders TO `analysts`; REVOKE SELECT ON TABLE main.sales.orders FROM `analysts`.",
      "GRANT and REVOKE are the core commands. DENY comes from legacy table access control; check the privileges docs for how Unity Catalog treats it.",
      "Row filter: a SQL function that returns a boolean, attached with ALTER TABLE t SET ROW FILTER f ON (col).",
      "Column mask: a SQL function that returns the masked value, attached with ALTER TABLE t ALTER COLUMN c SET MASK f.",
      "is_account_group_member('group') is the usual check inside filters and masks.",
      "ABAC policies apply filters and masks based on governed tags, so one rule covers every tagged column, including future tables.",
      "Run production jobs as a service principal, not as a person."
    ],
    docs: [
      ["Tables in Unity Catalog", "https://docs.databricks.com/aws/en/tables/"],
      ["Manage privileges", "https://docs.databricks.com/aws/en/data-governance/unity-catalog/manage-privileges/"],
      ["Row filters and column masks", "https://docs.databricks.com/aws/en/tables/row-and-column-filters"],
      ["ABAC policies", "https://docs.databricks.com/aws/en/data-governance/unity-catalog/abac/"]
    ] }
];

const CARDS = [
  ["s1","Control plane","The part of Databricks that runs in the Databricks account: web app, job scheduler, notebook and job metadata."],
  ["s1","Where does the data live?","In your own cloud object storage, not in the control plane."],
  ["s1","Delta Lake","Open table format: Parquet data files plus a transaction log that gives ACID transactions, time travel and history."],
  ["s1","Unity Catalog name","Three levels: catalog.schema.object, for example main.sales.orders."],
  ["s1","All purpose vs jobs compute","All purpose is for interactive work and stays up. Jobs compute is created for a run and terminates after, at a lower rate."],
  ["s1","Serverless SQL warehouse","SQL compute that starts in seconds and scales for many concurrent BI users with no cluster setup."],
  ["s1","Pool","A set of idle, ready instances that cuts cluster start time."],
  ["s2","COPY INTO","SQL command that loads new files from cloud storage into a table and skips files it already loaded."],
  ["s2","Auto Loader","Incremental file ingestion with spark.readStream.format(\"cloudFiles\"), tracked by a checkpoint."],
  ["s2","cloudFiles.schemaLocation","Where Auto Loader keeps the inferred schema and its history."],
  ["s2","Why are my JSON columns all strings?","Auto Loader infers JSON and CSV columns as strings by default. Set cloudFiles.inferColumnTypes or use schema hints."],
  ["s2","addNewColumns","Default schema evolution mode. The stream stops on a new column, updates the schema, and picks it up on restart."],
  ["s2","_rescued_data","Column that keeps values that did not match the schema, so nothing is silently lost."],
  ["s2","Directory listing vs file notification","Listing scans the folder. File notification uses cloud events and queues and scales to very large directories."],
  ["s2","trigger(availableNow=True)","Process all available data in as many batches as needed, then stop."],
  ["s2","Lakeflow Connect managed connector","Managed ingestion from SaaS apps and databases such as Salesforce or SQL Server, with little code."],
  ["s2","JDBC read","spark.read.format(\"jdbc\").option(\"url\", ...).option(\"dbtable\", ...).load()"],
  ["s3","Bronze, silver, gold","Raw with a schema, then cleaned and conformed, then aggregated for BI."],
  ["s3","DataFrame.union","Keeps duplicates like UNION ALL and matches columns by position."],
  ["s3","unionByName","Combines DataFrames by column name instead of position."],
  ["s3","Broadcast join","Send a small table to every executor so the big table is not shuffled. F.broadcast(df)."],
  ["s3","spark.sql.autoBroadcastJoinThreshold","Size limit for automatic broadcast joins, 10 MB by default. -1 disables it."],
  ["s3","spark.sql.shuffle.partitions","Number of partitions after a shuffle, 200 by default."],
  ["s3","dropDuplicates vs distinct","dropDuplicates([\"key\"]) keeps one row per key. distinct() compares every column."],
  ["s3","approx_count_distinct","Fast approximate count of unique values for large data."],
  ["s3","explode","Turns each element of an array column into its own row."],
  ["s3","View vs materialized view","A view runs its query every time. A materialized view stores the results and is refreshed."],
  ["s3","Streaming table","Table that processes new rows incrementally, each row once. Good for append only sources."],
  ["s3","EXPECT ... ON VIOLATION DROP ROW","Drops rows that fail the rule and records the count in pipeline metrics."],
  ["s3","EXPECT ... ON VIOLATION FAIL UPDATE","Stops the pipeline update when any row fails the rule."],
  ["s4","Depends on","The tasks that must finish before this task runs. Run if decides which outcomes count."],
  ["s4","If/else condition task","Branches the job on a value such as a parameter or a task value."],
  ["s4","For each task","Runs a nested task once for every item in a list."],
  ["s4","File arrival trigger","Starts a run when new files land in a volume or external location."],
  ["s4","Table update trigger","Starts a run when a source table is updated."],
  ["s4","Quartz cron","Syntax for complex schedules, used by Lakeflow Jobs scheduled triggers."],
  ["s4","Repair run","Reruns only the failed tasks and the tasks downstream of them."],
  ["s4","Task retries","Per task setting for how many times and how often to retry a failed task."],
  ["s5","Git folder","A Git repo cloned into the workspace (formerly Repos). Branch, commit, push, pull and merge from the UI."],
  ["s5","databricks.yml","The root configuration file of a bundle."],
  ["s5","Bundle target","An environment such as dev or prod, with its own overrides."],
  ["s5","${var.catalog}","How a bundle references a variable declared under variables."],
  ["s5","mode: development","Prefixes deployed resource names with your user name and pauses schedules."],
  ["s5","databricks bundle validate","Checks the bundle configuration before you deploy."],
  ["s5","databricks bundle deploy -t prod","Deploys the bundle to the prod target."],
  ["s6","Data skew in the Spark UI","A few tasks run far longer and read far more shuffle data than the rest."],
  ["s6","Spill","Data written out because a partition did not fit in memory. Seen as Spill (Memory) and Spill (Disk)."],
  ["s6","Liquid clustering","CLUSTER BY keys that replace partitioning and ZORDER and can change without a rewrite."],
  ["s6","Predictive optimization","Runs OPTIMIZE, VACUUM and ANALYZE automatically on Unity Catalog managed tables."],
  ["s6","OPTIMIZE vs VACUUM","OPTIMIZE compacts small files. VACUUM deletes unreferenced files after the retention period."],
  ["s6","Driver out of memory","Often caused by collect() on a large DataFrame. Write results to a table instead."],
  ["s6","%pip install","Notebook scoped library install that avoids conflicts with other notebooks on the cluster."],
  ["s7","Managed table DROP","Removes metadata and data. UNDROP can recover it for a limited time."],
  ["s7","External table DROP","Removes only the metadata. Files at the LOCATION stay."],
  ["s7","Minimum privileges to read a table","USE CATALOG, USE SCHEMA and SELECT."],
  ["s7","Privilege inheritance","A grant on a catalog or schema applies to everything inside, including objects created later."],
  ["s7","Row filter","Boolean SQL function attached with ALTER TABLE ... SET ROW FILTER."],
  ["s7","Column mask","SQL function attached with ALTER TABLE ... ALTER COLUMN ... SET MASK."],
  ["s7","ABAC policy","A central rule that filters or masks data based on governed tags."],
  ["s7","Service principal","A non human identity used to run production jobs and automation."]
];

// [section, question, [options], correctIndex, explanation]
const QUESTIONS = [
  ["s1","A notebook is moved from a classic cluster to serverless compute. Where does the compute run now?",
    ["In the customer's cloud account, the same as before","In a compute plane that Databricks manages in its own account","Inside the control plane's web application","On the user's own computer"],1,
    "Classic compute runs in your cloud account. Serverless compute runs in a compute plane managed by Databricks. Your data still stays in your own storage."],
  ["s1","A team needs quick rollbacks, an audit trail of changes and consistent governed access to the same tables. Which combination fits?",
    ["CSV files in DBFS with manual copies","Delta Lake ACID transactions and time travel, governed by Unity Catalog","Cloud storage only, queried ad hoc","Temporary views cached in memory"],1,
    "Delta Lake gives ACID writes, history and time travel. Unity Catalog adds consistent access control and audit. This mirrors an official sample question."],
  ["s1","Which unit does Databricks use to bill compute usage?",
    ["A DBU, a unit of processing capability per hour","The number of notebooks that were opened","The number of rows written to Delta tables","The number of users in the workspace"],0,
    "A Databricks Unit (DBU) measures processing capability per hour. The DBU rate depends on the compute type, so jobs compute and serverless have their own rates."],
  ["s1","Analysts run many small SQL dashboard queries during the day and want fast startup with no cluster management. What should they use?",
    ["A serverless SQL warehouse","A jobs cluster","An all purpose cluster with fixed workers","A single node cluster"],0,
    "Serverless SQL warehouses start in seconds and scale for concurrent BI users."],
  ["s1","Which name correctly references a table in Unity Catalog?",
    ["sales.orders","main.sales.orders","hive.main.sales.orders","dbfs:/sales/orders"],1,
    "Unity Catalog uses a three level namespace: catalog.schema.table."],
  ["s1","A SQL heavy job on classic compute runs slowly. The team wants faster query execution without changing any code. Which setting helps most?",
    ["Enable Photon on the compute","Set spark.sql.shuffle.partitions to 1","Rewrite the notebook in Scala","Add an init script"],0,
    "Photon is the Databricks native vectorized engine. It speeds up SQL and DataFrame work with no code changes."],

  ["s2","A source file was fixed in place after COPY INTO had already loaded it. The next COPY INTO run skips the file. Which option makes it load again?",
    ["COPY_OPTIONS ('force' = 'true')","FORMAT_OPTIONS ('header' = 'true')","Run VACUUM on the target table first","Add PATTERN = '*.csv' to the command"],0,
    "COPY INTO skips files it already loaded, even if they changed since. Setting force to true turns that check off and loads the files again."],
  ["s2","Which code starts an Auto Loader stream?",
    ["spark.read.format(\"autoloader\")","spark.readStream.format(\"cloudFiles\")","spark.readStream.format(\"delta\")","spark.read.format(\"stream\")"],1,
    "Auto Loader is the cloudFiles source on readStream."],
  ["s2","Auto Loader infers a column named amount as a string. The team wants it stored as DECIMAL(10,2) without writing the whole schema by hand. Which option?",
    ["cloudFiles.schemaHints","cloudFiles.schemaLocation","cloudFiles.useNotifications","cloudFiles.maxFilesPerTrigger"],0,
    "Schema hints override the inferred type for the columns you name, for example \"amount DECIMAL(10,2)\". The other columns keep their inferred types."],
  ["s2","An Auto Loader stream using the default schema evolution mode sees a new column in the source files. What happens?",
    ["The column is silently dropped","The stream stops, the schema is updated, and the column is included after restart","All rows go to a quarantine table","The stream keeps running and ignores the column forever"],1,
    "addNewColumns is the default. The stream fails on the new column, updates the stored schema, and picks it up when restarted."],
  ["s2","Which Auto Loader option sets where the inferred schema is stored?",
    ["cloudFiles.format","cloudFiles.schemaLocation","checkpointLocation only","mergeSchema"],1,
    "cloudFiles.schemaLocation stores the inferred schema and its evolution over time."],
  ["s2","Values that do not match the Auto Loader schema should be kept for later review. Where do they go?",
    ["The _rescued_data column","A separate error table created automatically","They are dropped","The checkpoint folder"],0,
    "The rescued data column captures values that did not fit the schema."],
  ["s2","A landing folder receives millions of files and directory listing is getting slow. Which Auto Loader setting helps?",
    ["Switch to file notification mode","Switch to COPY INTO","Reduce the number of workers","Use trigger(once=True)"],0,
    "File notification mode uses cloud events and queues instead of listing the directory."],
  ["s2","A streaming write must be able to restart after a failure and continue from where it stopped, without loading the same files twice. Which option must be set on the writer?",
    ["checkpointLocation","cloudFiles.schemaLocation","mergeSchema","overwriteSchema"],0,
    "The checkpoint records which files and offsets were already processed. On restart the stream continues from it, so each file is processed once."],
  ["s2","The team must ingest Salesforce objects into Unity Catalog tables with as little custom code as possible. What fits best?",
    ["A Python REST client in a notebook","A Lakeflow Connect managed connector for Salesforce","COPY INTO from exported CSV files","A JDBC read scheduled hourly"],1,
    "Lakeflow Connect managed connectors handle SaaS sources such as Salesforce with minimal code."],
  ["s2","A notebook reads a large PostgreSQL table with spark.read.format(\"jdbc\"). The Spark UI shows the whole read in one task. Which options split the read across workers?",
    ["partitionColumn, lowerBound, upperBound and numPartitions","cloudFiles.maxFilesPerTrigger and cloudFiles.format","spark.sql.shuffle.partitions and spark.default.parallelism","header and inferSchema"],0,
    "A JDBC read runs in one task unless you give a numeric partition column with bounds. Spark then opens several connections and reads the ranges in parallel."],
  ["s2","A pipeline consumes Databricks audit logs delivered to S3. What should the engineer expect about format, latency and overwrites?",
    ["JSON files, delivered within about 15 minutes, and files can be overwritten","CSV files, delivered in under a minute, never overwritten","Parquet files, delivered after 24 hours, overwrites disabled","JSON files, delivered weekly as a full replacement"],0,
    "This is one of the official sample questions. Audit log delivery is JSON, typically within 15 minutes, and files may be overwritten."],
  ["s2","Which statement about COPY INTO and Auto Loader is correct?",
    ["Only Auto Loader can load files incrementally","Both load files incrementally; Auto Loader scales better for very large or continuously arriving file sets","COPY INTO supports streaming triggers","Auto Loader cannot write to Unity Catalog tables"],1,
    "COPY INTO suits simpler batch loads. Auto Loader is built for large volumes and continuous arrival."],
  ["s2","Before a Lakeflow Connect managed connector can ingest from a SaaS source, which object must exist?",
    ["A Unity Catalog connection that holds the source credentials","An init script on an all purpose cluster","A DBFS mount point","A Kafka topic"],0,
    "Managed connectors read the source through a Unity Catalog connection. The ingestion pipeline then writes streaming tables. Only database sources also need an ingestion gateway."],
  ["s2","A notebook reads a Kafka topic with spark.readStream.format(\"kafka\"). The value column arrives as bytes. What is the usual next step?",
    ["Cast value to STRING and parse it, for example with from_json","Set cloudFiles.format to json","Run COPY INTO on the topic","Turn on Photon"],0,
    "Kafka delivers key and value as binary. Cast them to string, then parse the JSON with from_json and a schema."],
  ["s2","An analyst works only in a SQL warehouse and wants new JSON files from a volume loaded incrementally. Which statement fits?",
    ["CREATE STREAMING TABLE events AS SELECT * FROM STREAM read_files('/Volumes/main/raw/events', format => 'json')","CREATE VIEW events AS SELECT * FROM json.`/Volumes/main/raw/events`","CREATE TABLE events AS SELECT * FROM read_files('/Volumes/main/raw/events', format => 'json')","INSERT OVERWRITE events SELECT * FROM events"],0,
    "A streaming table in Databricks SQL uses Auto Loader through read_files. Each refresh loads only the new files. The CREATE TABLE AS version would be a one time batch load."],
  ["s2","A teammate has a 5 MB CSV export and wants it as a Unity Catalog table today with no code. What is the easiest way?",
    ["Upload it with the Create or modify table from file upload UI","Set up a Lakeflow Connect managed connector","Configure Auto Loader with file notification mode","Write a bundle and deploy it"],0,
    "The file upload UI creates or updates a table from small local files. It suits one off loads, not automated pipelines."],
  ["s2","A column named raw holds JSON as a string, like {\"user\": {\"id\": 7}}. Which SQL pulls out the id without defining a schema?",
    ["SELECT raw:user.id FROM events","SELECT raw.user.id FROM events","SELECT explode(raw) FROM events","SELECT raw['user']['id'] FROM events"],0,
    "The colon syntax reads fields from a JSON string column. Dot syntax works on struct columns, not on strings."],
  ["s2","Which option is required for every Auto Loader stream?",
    ["cloudFiles.format","cloudFiles.useNotifications","cloudFiles.schemaHints","cloudFiles.maxBytesPerTrigger"],0,
    "Auto Loader must know the file format, such as json, csv or parquet. The other cloudFiles options are optional."],

  ["s3","In PySpark, df1.union(df2) is used on two DataFrames with the same columns. What happens to duplicate rows?",
    ["They are removed, like SQL UNION","They are kept, like SQL UNION ALL","The call fails","Only the first DataFrame's duplicates are removed"],1,
    "DataFrame.union keeps duplicates and matches by position. Add distinct() to remove them."],
  ["s3","Two DataFrames have the same columns in a different order. Which method combines them correctly?",
    ["union","unionByName","crossJoin","join on all columns"],1,
    "unionByName matches columns by name instead of position."],
  ["s3","A large fact table is joined to a 5 MB lookup table and the join shuffles a lot of data. What is the best fix?",
    ["Use a cross join","Broadcast the lookup table","Increase spark.sql.shuffle.partitions to 5000","Collect the fact table to the driver"],1,
    "Broadcasting the small table avoids shuffling the large one."],
  ["s3","What does setting spark.sql.autoBroadcastJoinThreshold to -1 do?",
    ["Broadcasts every table","Disables automatic broadcast joins","Sets the threshold to 1 MB","Forces sort merge joins to fail"],1,
    "The threshold controls automatic broadcasting. -1 turns it off."],
  ["s3","A small job runs 200 tiny tasks after every shuffle. Which setting is most directly responsible?",
    ["spark.executor.memory","spark.sql.shuffle.partitions","spark.driver.memory","spark.sql.autoBroadcastJoinThreshold"],1,
    "spark.sql.shuffle.partitions defaults to 200. Lower it for small data, or let adaptive query execution coalesce partitions."],
  ["s3","Keep one row per order_id from a DataFrame that has repeated orders. Which call?",
    ["df.distinct()","df.dropDuplicates([\"order_id\"])","df.groupBy(\"order_id\")","df.dropna()"],1,
    "dropDuplicates with a subset keeps one row per key. distinct compares every column."],
  ["s3","You need a fast, approximate number of unique users across billions of rows. Which function?",
    ["count(DISTINCT user_id)","approx_count_distinct(user_id)","sum(user_id)","collect_set(user_id)"],1,
    "approx_count_distinct trades a small error for much better speed."],
  ["s3","A column items holds an array of products. You need one row per product. Which function?",
    ["split","explode","flatten","pivot"],1,
    "explode creates one row per array element."],
  ["s3","A BI dashboard reads the same expensive aggregation many times a day. The result can be a few minutes old. Which gold object fits?",
    ["A view","A materialized view","A temporary view","A streaming table with no aggregation"],1,
    "A materialized view stores precomputed results and is refreshed, so reads are fast."],
  ["s3","A pipeline source table receives updates and deletes, not only new rows. Which pipeline dataset type should hold its downstream aggregate?",
    ["A materialized view","A streaming table","A temporary view","An external table"],0,
    "Streaming tables expect append only sources. When the source has updates or deletes, use a materialized view, which is recomputed or refreshed incrementally."],
  ["s3","A pipeline expectation is written as CONSTRAINT has_email EXPECT (email IS NOT NULL) with no ON VIOLATION clause. A row with a null email arrives. What happens?",
    ["The row is written to the target and the violation is counted in the pipeline metrics","The row is dropped","The whole update fails","The row is moved to the _rescued_data column"],0,
    "With no action set, the expectation only warns. Invalid rows are still written to the target, and the number of violations shows in the data quality metrics."],
  ["s3","Silver rows must not have a null customer_id. Which PySpark call removes those rows?",
    ["df.na.drop(subset=[\"customer_id\"])","df.fillna(0)","df.dropDuplicates([\"customer_id\"])","df.na.fill(\"unknown\", [\"customer_id\"])"],0,
    "na.drop with a subset removes rows where those columns are null. fillna and na.fill replace nulls instead of removing the rows."],
  ["s3","A silver Delta table must reject any write where quantity is negative. Which statement enforces this on the table itself?",
    ["ALTER TABLE silver.orders ADD CONSTRAINT qty_positive CHECK (quantity >= 0)","ALTER TABLE silver.orders SET TBLPROPERTIES ('quantity' = 'positive')","CREATE VIEW silver.orders_ok AS SELECT * FROM silver.orders WHERE quantity >= 0","OPTIMIZE silver.orders"],0,
    "A CHECK constraint is checked on every write. A write that contains a failing row is rejected, so bad data never lands in the table."],
  ["s3","Every order must stay in the result even when the customer lookup table has no matching row. Which join?",
    ["orders.join(customers, \"customer_id\", \"left\")","orders.join(customers, \"customer_id\", \"inner\")","orders.crossJoin(customers)","orders.join(customers, \"customer_id\", \"left_semi\")"],0,
    "A left join keeps every row from the left DataFrame and fills the right side with nulls when there is no match."],
  ["s3","Two DataFrames must be joined on both store_id and sale_date. Which call is correct?",
    ["sales.join(targets, [\"store_id\", \"sale_date\"])","sales.join(targets, \"store_id\").join(targets, \"sale_date\")","sales.union(targets)","sales.join(targets, sales.store_id == targets.sale_date)"],0,
    "Pass a list of column names to join on several keys at once. Joining twice would multiply the rows."],
  ["s3","A column full_name holds values like \"Ana Cruz\". Which expression turns it into an array of the two parts?",
    ["split(col(\"full_name\"), \" \")","explode(col(\"full_name\"))","substring(col(\"full_name\"), 1, 3)","concat_ws(\" \", col(\"full_name\"))"],0,
    "split breaks a string into an array using a pattern. explode then turns an array into rows if needed."],
  ["s3","A column price arrived as a string in bronze. Which call writes it to silver as a decimal?",
    ["df.withColumn(\"price\", col(\"price\").cast(\"decimal(10,2)\"))","df.withColumnRenamed(\"price\", \"decimal\")","df.select(\"price\").distinct()","df.filter(col(\"price\").isNotNull())"],0,
    "withColumn with cast changes the column's type in place. Standardizing types is a core bronze to silver step."],
  ["s3","Which DataFrame method returns count, mean, standard deviation, min, the quartiles and max for numeric columns in one call?",
    ["df.summary()","df.explain()","df.printSchema()","df.collect()"],0,
    "summary() gives the basic statistics plus the 25%, 50% and 75% percentiles. describe() is similar but without the percentiles."],
  ["s3","A bronze table has several rows per order_id. Silver must keep only the newest row for each order_id, based on updated_at. Which approach works?",
    ["Use row_number() over a window partitioned by order_id and ordered by updated_at descending, then keep the rows where it equals 1","Call df.distinct()","Call df.dropDuplicates() with no columns","Call df.groupBy(\"order_id\").count()"],0,
    "A window function ranks the rows inside each order_id. Keeping rank 1 keeps the newest row. distinct() only removes exact duplicates."],
  ["s3","A job fails with an out of memory error inside the executors during a very large join. Which change is the most direct fix?",
    ["Raise spark.executor.memory or use worker nodes with more memory","Raise spark.driver.memory","Set spark.sql.shuffle.partitions to 1","Cache every DataFrame in the notebook"],0,
    "Executor memory holds the partitions being processed. More memory per executor, or more partitions so each one is smaller, stops the error. Driver memory does not help here."],

  ["s4","A cleanup task must run at the end of a job even when an earlier task failed. Which Run if setting should the cleanup task use?",
    ["All done","All succeeded","At least one succeeded","None failed"],0,
    "All done runs the task after every dependency finished, whatever their status. All succeeded is the default and would skip the cleanup after a failure."],
  ["s4","Task A computes a row count that task B needs later in the same job run. How should A pass it to B?",
    ["Set it with dbutils.jobs.taskValues.set in A and read it with dbutils.jobs.taskValues.get in B","Print it in A and have B parse the driver log","Keep it in a Python variable, since tasks share memory","Store it in a cluster environment variable"],0,
    "Task values pass small values between tasks in a run. They can also feed If/else condition tasks and dynamic value references."],
  ["s4","The same notebook must run once for each of 30 store IDs. Which task type fits?",
    ["For each task","If/else condition task","Pipeline task","Dashboard task"],0,
    "For each runs a nested task once per item, with optional concurrency."],
  ["s4","Files arrive in a volume at unpredictable times. The job should start as soon as new files land. Which trigger?",
    ["Scheduled trigger every hour","File arrival trigger","Continuous trigger on a SQL warehouse","Manual run"],1,
    "File arrival triggers are data driven and start the job when new files appear."],
  ["s4","A job must run at 6 AM Manila time every weekday. Which trigger fits?",
    ["A scheduled trigger with a cron expression and the Asia/Manila time zone","A file arrival trigger","A continuous trigger","A table update trigger"],0,
    "Scheduled triggers use a simple interval or Quartz cron syntax, and you set the time zone with them. The other triggers react to data, not to the clock."],
  ["s4","A scheduled job must not run during a two week code freeze, but the schedule must be kept for later. What should the engineer do?",
    ["Pause the job's schedule, then resume it after the freeze","Delete the job and recreate it later","Set max concurrent runs to 0","Remove all tasks from the job"],0,
    "A schedule or trigger can be paused and resumed in the job settings. The job and its run history stay in place."],
  ["s4","A task calls an API that fails briefly now and then. What should be configured?",
    ["Task retries with a retry interval","A second job","Continuous mode","A bigger cluster"],0,
    "Retries handle transient failures without manual reruns."],
  ["s4","A task sometimes hangs for hours. The team wants it stopped after 30 minutes and tried again once. Which settings?",
    ["A task timeout of 30 minutes with a retry policy that retries on timeout","Max concurrent runs set to 30","A continuous trigger","A For each task with concurrency 2"],0,
    "The task timeout marks a run as Timed Out after the limit. A retry policy with Retry on timeout enabled then runs the task again."],
  ["s4","The team wants a warning when a job runs longer than 2 hours, even if it finishes successfully later. Which feature?",
    ["A duration warning threshold with a notification destination","A task retry policy","A file arrival trigger","A repair run"],0,
    "Set an expected duration for the job and turn on the Duration warning notification. It goes to email or a destination such as Slack, Teams, PagerDuty or a webhook."],
  ["s4","A nightly job must trigger an existing job owned by another team as one of its steps. Which task type?",
    ["A Run job task that points to the other job","A notebook task that copies their notebooks into this job","A pipeline task","A dashboard task"],0,
    "The Run job task runs another job as a step, so teams can chain jobs without copying tasks."],
  ["s4","A Lakeflow Spark Declarative Pipeline must finish refreshing before a notebook reads its output. How is this done in one job?",
    ["Add a pipeline task and make the notebook task depend on it","Run the pipeline from the notebook with %run","Schedule the pipeline and the notebook at the same minute","Convert the pipeline into a SQL warehouse query"],0,
    "A pipeline task runs a pipeline update as a step. The notebook task's Depends on setting then waits for it."],
  ["s4","A saved SQL query must run on a SQL warehouse every hour as part of a job. Which task type?",
    ["A SQL task that runs the saved query on a SQL warehouse","A Python wheel task","A dbt task","A JAR task"],0,
    "SQL tasks run a saved query, a SQL file or an alert on a SQL warehouse, so analysts' work can be part of a job."],
  ["s4","The same job must run against the dev catalog and the prod catalog. The catalog name must not be hard coded in the notebooks. Which feature?",
    ["Job parameters, read in the notebook with dbutils.widgets.get","Two copies of every notebook","Cluster tags","Init scripts"],0,
    "Job parameters are passed to every task in the run. Notebooks read them as widgets, so one job definition serves both catalogs."],
  ["s4","Which location can a file arrival trigger watch?",
    ["A Unity Catalog volume or external location","The DBFS root","A Kafka topic","A Git folder"],0,
    "File arrival triggers watch Unity Catalog external locations and volumes, including subpaths. DBFS paths are not supported."],

  ["s5","An engineer wants to try a risky change in a Git folder without touching the main branch. What should they do first?",
    ["Create a new branch in the Git folder and switch to it","Commit straight to main","Delete the main branch","Export the notebook as HTML"],0,
    "Git folders let you create and switch branches from the Git dialog. Work on the branch, then open a pull request on your Git provider."],
  ["s5","A bundle must define one job and one pipeline. Where are they declared?",
    ["Under the resources mapping in databricks.yml","In a Dockerfile at the bundle root","In the first cell of the notebook","In a Unity Catalog volume"],0,
    "Bundle resources such as jobs and pipelines are declared under resources in databricks.yml, or in YAML files it includes."],
  ["s5","After deploying a bundle, the engineer wants to remove every job and pipeline it created from the workspace. Which command?",
    ["databricks bundle destroy","databricks bundle deploy --delete","databricks workspace rm","databricks bundle summary"],0,
    "bundle destroy deletes the resources and files that a previous deploy created for that target."],
  ["s5","A new project needs a starting bundle with a sample job and pipeline. Which command creates one from a template?",
    ["databricks bundle init","databricks bundle run","databricks bundle destroy","databricks configure"],0,
    "bundle init creates a project from a template such as default-python. Then you edit databricks.yml, validate and deploy."],
  ["s5","Dev and prod must write to different catalogs from the same code. What is the recommended approach?",
    ["Keep two copies of every notebook","Declare a catalog variable and override it per target, referenced as ${var.catalog}","Edit the notebook before each deploy","Use one catalog for both"],1,
    "Variables with target overrides promote the same code across environments."],
  ["s5","What does mode: development do for a bundle target?",
    ["Deletes resources after each run","Prefixes resource names with the user and pauses schedules","Runs everything as a service principal","Disables Git integration"],1,
    "Development mode keeps each developer's copy separate and stops schedules from firing."],
  ["s5","A team wants modular, versioned ETL that can be promoted through environments with CI/CD. What fits best?",
    ["Store code in Unity Catalog models","Define the resources in a bundle, version it in Git and deploy it per target","Copy notebooks between workspaces by hand","Package everything in one notebook in a volume"],1,
    "This mirrors an official sample question. Bundles in Git give repeatable, promotable deployments."],
  ["s5","A CI pipeline deploys a bundle to production. Where should the credentials it uses be kept?",
    ["In the CI system's secret store, passed to the CLI as environment variables","Hard coded in databricks.yml","Committed in a .env file in the repo","In a comment in the notebook"],0,
    "Keep secrets out of the repo. CI tools such as GitHub Actions inject them as environment variables, and the pipeline should run as a service principal."],
  ["s5","A production Git folder in the workspace must get the latest main branch after each merge, without anyone clicking Pull. What is the recommended way?",
    ["Have the CI workflow or a scheduled job update the Git folder through the Repos API","Ask each engineer to pull it by hand","Delete and re-clone the folder every night","Turn off Git integration for production"],0,
    "The Repos API updates a Git folder to a branch or commit. A CI tool or a scheduled job can call it after each merge. Bundles are the recommended path for new projects."],
  ["s5","A bundle variable must use a different value for one deploy, without editing any file. How?",
    ["databricks bundle deploy --var=\"catalog=test\"","Edit the notebook and redeploy","Run databricks bundle destroy first","Change the value in Catalog Explorer"],0,
    "The --var flag sets a variable for that command. Command line values win over environment variables, target overrides and defaults."],

  ["s6","A job doubled in duration. In the Spark UI most tasks take under 30 seconds but one takes over 10 minutes and reads 5 GB of shuffle data. What is the problem and a fix?",
    ["Too few executors; add nodes","Data skew; make sure adaptive query execution skew join handling is on","Too many shuffle partitions; reduce them","Slow storage; change file format"],1,
    "One long task with much larger shuffle reads is skew. This mirrors an official sample question."],
  ["s6","A stage shows large Spill (Disk) values. What does that indicate?",
    ["Partitions did not fit in memory and were written to disk","The job wrote output files","Broadcast joins were used","The cluster autoscaled"],0,
    "Spill means memory was not enough for the partitions. More partitions or more memory helps."],
  ["s6","Where do you compare today's job duration with previous runs?",
    ["The Lakeflow Jobs run history for the job","The cluster driver logs","Catalog Explorer","The notebook revision history"],0,
    "The job's runs view shows durations and statuses over time."],
  ["s6","Which statement about liquid clustering is true?",
    ["It requires partitioning to be set first","Its clustering keys can change without rewriting the whole table","It only works on external tables","It replaces VACUUM"],1,
    "Liquid clustering replaces partitioning and ZORDER, and keys can be changed later."],
  ["s6","What does predictive optimization do?",
    ["Predicts query results","Runs maintenance such as OPTIMIZE, VACUUM and ANALYZE automatically on Unity Catalog managed tables","Auto scales SQL warehouses","Rewrites SQL queries"],1,
    "Predictive optimization handles table maintenance for managed tables."],
  ["s6","A notebook fails with a driver out of memory error right after df.collect() on a large DataFrame. What should change?",
    ["Add more worker nodes","Avoid collect(); write the result to a table or use limit()","Increase shuffle partitions","Turn off Photon"],1,
    "collect() brings all data to the driver. Keep large results distributed."],
  ["s6","Two notebooks on the same cluster need different versions of a library. What avoids the conflict?",
    ["Install both on the cluster","Use notebook scoped libraries with %pip install","Restart the cluster between runs","Use a SQL warehouse"],1,
    "Notebook scoped libraries isolate dependencies per notebook."],
  ["s6","A job cluster fails to start with a message that the instance type is not available in the region. Where should the engineer look, and what is a fix?",
    ["Check the cluster event log, then pick another instance type or use serverless compute","Run OPTIMIZE on the tables the job reads","Increase spark.sql.shuffle.partitions","Restart the SQL warehouse"],0,
    "Cluster start failures show their cause in the event log. Cloud capacity and quota problems are fixed by changing the instance type, using a pool, or moving to serverless."],
  ["s6","A team runs VACUUM with RETAIN 0 HOURS to free storage. The command fails with a retention check error. Why?",
    ["A safety check blocks retention shorter than 7 days because it can break time travel and running queries","VACUUM needs OPTIMIZE to run first","VACUUM only works on external tables","RETAIN must be given in minutes"],0,
    "Delta blocks short retention by default (the retentionDurationCheck). Files that active readers or older versions still need would be deleted."],

  ["s7","A managed table was dropped by mistake an hour ago. Which command brings it back?",
    ["UNDROP TABLE main.sales.orders","RESTORE TABLE main.sales.orders TO VERSION AS OF 1","CREATE TABLE main.sales.orders","VACUUM main.sales.orders"],0,
    "UNDROP recovers a dropped Unity Catalog table within the recovery period, 7 days by default. RESTORE only works on a table that still exists."],
  ["s7","A new managed table is created in a schema that has no managed location of its own. Where are its files stored?",
    ["In the catalog's managed location, or the metastore root storage if the catalog has none","In the DBFS root","On the driver node's local disk","In the creating user's home folder"],0,
    "Managed storage is chosen from the schema first, then the catalog, then the metastore. Unity Catalog manages the files at that location."],
  ["s7","An analyst can read a table but gets a permission error when the query calls a Unity Catalog SQL function. Which privilege is missing?",
    ["EXECUTE on the function","MODIFY on the table","CREATE FUNCTION on the schema","USE CATALOG on the catalog"],0,
    "Calling a function needs EXECUTE on it, plus USE CATALOG and USE SCHEMA on its parents. The analyst already has those, since the table read works."],
  ["s7","SELECT is granted on a catalog to the analysts group. New tables are created in it later. What access do analysts have to the new tables?",
    ["None until granted again","SELECT, because privileges are inherited by objects inside the catalog","Ownership","Only tables that existed at grant time"],1,
    "Unity Catalog privileges are inherited downward, including future objects."],
  ["s7","Which statement removes the analysts group's read access to a table?",
    ["DELETE SELECT ON TABLE t FROM analysts","REVOKE SELECT ON TABLE t FROM `analysts`","GRANT NONE ON TABLE t TO analysts","DROP GRANT SELECT ON t"],1,
    "REVOKE privilege ON object FROM principal."],
  ["s7","Each department should see only its own rows in a shared table. What should be used?",
    ["A column mask","A row filter function attached with ALTER TABLE ... SET ROW FILTER","A separate table per region","VACUUM"],1,
    "Row filters return a boolean per row, often using is_account_group_member."],
  ["s7","Show the full SSN only to the hr group and a masked value to everyone else. What should be used?",
    ["A column mask on the ssn column","A row filter","A temporary view","An external table"],0,
    "Column masks return the real or masked value based on who is querying."],
  ["s7","Hundreds of tables have columns tagged pii. One central rule should mask all of them, including future tables. What should be implemented?",
    ["ALTER COLUMN SET MASK on every table","An ABAC policy that masks columns with the governed pii tag","A dynamic view for each table","A row filter on each schema"],1,
    "ABAC policies apply masks and filters based on governed tags, centrally and at scale."],
  ["s7","A production job should not run under a person's account. What identity should it use?",
    ["A shared personal login","A service principal","The workspace admin's account","An anonymous user"],1,
    "Service principals are non human identities for automation."],
  ["s7","Which command converts an external table to a Unity Catalog managed table?",
    ["ALTER TABLE t SET MANAGED","CONVERT TO DELTA t","CREATE TABLE t CLONE","ALTER TABLE t SET LOCATION"],0,
    "ALTER TABLE ... SET MANAGED moves an external table under Unity Catalog management."],
  ["s7","Raw PDF files must be stored and governed in Unity Catalog, and a job must write into that location. Which object and privileges?",
    ["A volume, with READ VOLUME and WRITE VOLUME granted","A managed table, with MODIFY granted","A view, with SELECT granted","A Delta Sharing share"],0,
    "Volumes govern non tabular files such as PDFs, images and CSVs. READ VOLUME and WRITE VOLUME control access to the files."],
  ["s7","A column mask function is attached to a phone column. What must the function return?",
    ["A value of the same type as the column, masked or unchanged","A boolean that says whether the row is visible","A list of allowed users","Nothing, it only logs the access"],0,
    "A column mask returns the value the user sees, so its return type matches the column. A row filter is the one that returns a boolean."],
  ["s7","A view must show the email column only to members of the support group and the text REDACTED to everyone else. Which function goes inside the view definition?",
    ["is_account_group_member('support')","current_catalog()","session_user() = 'support'","GRANT SELECT"],0,
    "Dynamic views use is_account_group_member inside a CASE expression to decide what each user sees. It checks account level group membership."],
  ["s7","Which kind of group should be used when granting privileges in Unity Catalog?",
    ["Account level groups","Workspace local groups","Cloud IAM roles","Email distribution lists"],0,
    "Unity Catalog grants work with account level users, groups and service principals. Workspace local groups cannot be granted access to Unity Catalog data."]
];

const RENAMES = [
  ["Delta Live Tables (DLT)","Lakeflow Spark Declarative Pipelines","Also seen as Lakeflow Declarative Pipelines"],
  ["CREATE LIVE TABLE","CREATE MATERIALIZED VIEW","Batch style pipeline dataset"],
  ["CREATE STREAMING LIVE TABLE","CREATE STREAMING TABLE","Incremental pipeline dataset"],
  ["APPLY CHANGES INTO","AUTO CDC","Change data capture in pipelines"],
  ["Databricks Workflows, Jobs","Lakeflow Jobs",""],
  ["Databricks Repos","Databricks Git folders",""],
  ["Databricks Asset Bundles (DABs)","Declarative Automation Bundles","Same databricks.yml and bundle CLI commands"],
  ["SQL endpoint","SQL warehouse",""],
  ["Data Explorer","Catalog Explorer","Where you browse tables, owners and permissions"],
  ["Lakehouse Platform","Data Intelligence Platform","The exam's name for the platform"],
  ["Hive metastore, DBFS paths","Unity Catalog tables and volumes","Older questions use dbfs:/user/hive/warehouse"]
];

const HANDSON = [
  "Create a catalog, schema and managed table in Unity Catalog, then query it with a three level name",
  "Upload files to a volume and load them with COPY INTO, then run it again and confirm nothing is duplicated",
  "Build an Auto Loader stream with a schema location, add a file with a new column, and watch schema evolution",
  "Clean a bronze table into silver: cast types, handle nulls, dropDuplicates, and write the result",
  "Join a fact table to a small lookup with a broadcast join and compare the plan in the Spark UI",
  "Create a view, a materialized view and a streaming table and note how each refreshes",
  "Add expectations to a pipeline with DROP ROW and FAIL UPDATE and read the data quality metrics",
  "Build a Lakeflow Job with three dependent tasks, a retry, an If/else task and a file arrival trigger",
  "Clone a repo into a Git folder, create a branch, commit and push, then open a pull request",
  "Create a small bundle with dev and prod targets and a catalog variable, then run validate and deploy",
  "GRANT and REVOKE access for a group, then add a row filter and a column mask"
];

const RESOURCES = [
  { group: "Official exam pages", items: [
    ["Data Engineer Associate certification page", "https://www.databricks.com/learn/certification/data-engineer-associate", "Exam facts, section weights, registration steps"],
    ["Associate exam guide (PDF)", "https://www.databricks.com/sites/default/files/2026-05/databricks-certified-data-engineer-associate-exam-guide-may-2026-000.pdf", "The full outline and sample questions. Check it again two weeks before your exam."],
    ["AI Prep Guide (PDF)", "https://www.databricks.com/sites/default/files/2026-06/ai-prep-guide-any-databricks-certification.pdf", "Databricks' own prompts for studying with an AI chatbot"],
    ["Register on Webassessor", "http://webassessor.com/databricks", "Use the same email as your Databricks Academy account if you have a festival voucher"],
    ["Certification FAQ", "https://www.databricks.com/learn/certification/faq", ""]
  ]},
  { group: "Training", items: [
    ["Databricks Academy", "https://www.databricks.com/learn/training/home", "Self paced courses"],
    ["Advanced Learning Festival, Sep 16 to Oct 14, 2026", "https://community.databricks.com/t5/learning-events/databricks-advanced-learning-festival-september-16-october-14/ec-p/166157", "Finish the Associate Data Engineering pathway in the window for 50% off a certification. Vouchers are emailed on Oct 19."],
    ["Databricks Free Edition", "https://www.databricks.com/learn/free-edition", "Free workspace for the hands-on list"]
  ]},
  { group: "Community study guides", items: [
    ["Alex Cole's resource guide for the Associate exam", "https://www.alexcole.net/databricks-data-engineer-associate-2026-resource-guide/", "Docs, demos and courses mapped to each objective"]
  ]}
];

const ACADEMY = [
  "Data Ingestion with Lakeflow Connect",
  "Deploy Workloads with Lakeflow Jobs",
  "Build Data Pipelines with Lakeflow Spark Declarative Pipelines",
  "DevOps Essentials for Data Engineering"
];

// ---------- site settings ----------
const SITE = {
  repo: "czekinah/databricks-de-associate-reviewer",
  notesIssue: 1,
  examDay: "2026-10-17",
  examDayLabel: "Saturday, October 17, 2026"
};

// ---------- exam tips ----------
const TIPS = [
  { title: "Before you book", items: [
    "Book on Webassessor with the same email as your Databricks Academy account. Festival vouchers only work for that email.",
    "Run the Kryterion system check on the computer you will use: kryterion.com/systemcheck. Do it again the day before.",
    "Online proctored exams can be rescheduled up to 24 hours before your slot. Test centers need 72 hours.",
    "Reread the exam guide two weeks before your date, around October 3 for an October 17 exam. Databricks updates it when the exam changes."
  ]},
  { title: "How to study", items: [
    "Study by weight. Ingestion and Transformation are 43% of the exam, so they get the most hours.",
    "Do every hands-on task once in Databricks Free Edition. Scenario questions are easier when you have clicked through the real screens.",
    "Learn the current names. Older practice sets still say DLT, Repos and SQL endpoint; the exam uses Lakeflow and Git folders.",
    "Take a timed mock exam, then spend more time reviewing the ones you missed than you spent taking it.",
    "Book the exam only after you score 80% or higher on two mock runs in a row."
  ]},
  { title: "During the exam", items: [
    "You get 90 minutes for 45 scored questions, about 2 minutes each. There may be a few unscored questions too, with extra time already added.",
    "Read the last sentence of the question first so you know what it is asking, then read the scenario.",
    "Watch the qualifiers: least operational overhead, minimal code, most cost effective. They usually point to a managed or serverless option.",
    "Cross out the two options that are clearly wrong, then compare the last two against the exact requirement.",
    "Answer every question. Mark the unsure ones for review and come back if time allows.",
    "Code is shown in SQL when possible, otherwise Python."
  ]},
  { title: "Exam day checklist", items: [
    "Valid government ID ready.",
    "A quiet, private room and a clear desk. Check the Kryterion rules for what the camera needs to see.",
    "Laptop charged and plugged in, other apps closed, notifications off.",
    "Log in 15 minutes early.",
    "No notes or aids are allowed, including a second screen."
  ]},
  { title: "When it feels like too much", items: [
    "Pick the smallest next step: one flashcard deck or one section quiz. Starting is the hard part.",
    "Compare yourself with where you were last week, not with your classmates.",
    "A good night of sleep before the exam does more than one more late night of review.",
    "Ask the batch. Someone else is stuck on the same topic, and explaining it helps both of you."
  ]},
  { title: "After the exam", items: [
    "You see an unofficial result right away. For a pass, Databricks reviews the proctor recording before the badge is issued.",
    "The badge arrives by email from Accredible and shows up at credentials.databricks.com.",
    "If it does not go your way, you can retake after 14 days. The section breakdown shows you exactly what to study, and you will already know the format.",
    "The certification is valid for 2 years."
  ]}
];

// ---------- study calendar to exam day ----------
// type: study | check | mock | rest | exam | deadline
const PLAN = [
  ["2026-09-25","study","Start: read Section 3 notes (Transformation, 22%) and do its flashcards"],
  ["2026-09-26","study","Section 3 quiz and the bronze to silver hands-on task"],
  ["2026-09-27","study","Section 2 notes (Ingestion, 21%): COPY INTO, Auto Loader, Lakeflow Connect"],
  ["2026-09-28","study","Section 2 flashcards and quiz, Auto Loader hands-on task"],
  ["2026-09-29","study","Academy course: Data Ingestion with Lakeflow Connect"],
  ["2026-09-30","study","Academy course: Build Data Pipelines with Lakeflow Spark Declarative Pipelines"],
  ["2026-10-01","check","Quick 10 on Sections 2 and 3. Redo anything under 80%"],
  ["2026-10-02","study","Section 4 notes (Lakeflow Jobs, 16%) and the jobs hands-on task"],
  ["2026-10-03","check","Reread the official exam guide for changes (two weeks out)"],
  ["2026-10-04","study","Academy course: Deploy Workloads with Lakeflow Jobs"],
  ["2026-10-05","study","Section 7 notes (Governance, 15%): grants, row filters, column masks"],
  ["2026-10-06","study","Section 7 quiz and the GRANT and REVOKE hands-on task"],
  ["2026-10-07","study","Section 5 notes (CI/CD, 10%) and Academy course: DevOps Essentials"],
  ["2026-10-08","study","Section 6 notes (Troubleshooting, 10%) and Section 1 (Platform, 6%)"],
  ["2026-10-09","check","Section quizzes for 1, 5 and 6"],
  ["2026-10-10","mock","Mock exam 1, timed. Review every miss"],
  ["2026-10-11","study","Repair day: reread notes for your two weakest sections"],
  ["2026-10-12","study","Renamed terms review and all flashcards not yet known"],
  ["2026-10-13","mock","Mock exam 2, timed"],
  ["2026-10-14","deadline","Festival ends. Last day to finish the four Associate courses for the voucher"],
  ["2026-10-15","check","Quick 10 twice, then light review only"],
  ["2026-10-16","rest","Run the Kryterion system check, prepare your ID and room, sleep early"],
  ["2026-10-17","exam","Exam day. Log in 15 minutes early"],
  ["2026-10-19","deadline","Festival vouchers are emailed to Academy accounts"]
];
